hdfs-client-k8s:
  image:
    repository: docker.registry:5000/gcr.io/byond-infinity-platform/integrity-hdfs
    tag: 2.9.2
hdfs-datanode-k8s:
  image:
    repository: docker.registry:5000/gcr.io/byond-infinity-platform/integrity-hdfs-datanode
    tag: 2.9.2
hdfs-journalnode-k8s:
  image:
    repository: docker.registry:5000/gcr.io/byond-infinity-platform/integrity-hdfs-namenode
    tag: 2.9.2
  initContainers:
    repository: docker.registry:5000/busybox
    tag: 1.27.1
hdfs-namenode-k8s:
  image:
    repository: docker.registry:5000/gcr.io/byond-infinity-platform/integrity-hdfs-namenode
    tag: 2.9.2
zookeeper:
  image:
    repository: docker.registry:5000/gcr.io/google_samples/k8szk
    tag: v3