hdfs-datanode-k8s:
  javaResources:
    #xms and xmx in mb
    xms: 128
    xmx: 5120
  resources:
    limits:
      cpu: 1
      memory: 6G
    requests:
      cpu: 500m
      memory: 6G

hdfs-journalnode-k8s:
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 600Mi

hdfs-namenode-k8s:
  javaResources:
    #xms and xmx in mb
    xms: 128
    xmx: 3096
  resources:
    limits:
      cpu: 1
      memory: 4G
    requests:
      cpu: 500m
      memory: 4G

zookeeper:
  resources:
    limits:
      cpu: 1
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi

global:
  # Where on the local FS where hdfs data will be stored
  dataNodeHostPath:
    - /hadoop-data
