{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  labels:
    app: minio-gateway
    chart: {{ template "hdfs-k8s.subchart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  accesskey: {{ .Values.accessKey | b64enc }}
  secretkey: {{ .Values.secretKey | b64enc }}
{{- end }}